#!/bin/bash
# /etc/init.d/piweather

### BEGIN INIT INFO
# Provides:          piweather
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Example initscript
# Description:       This service is used to manage piweather
### END INIT INFO
#`date +\%H\:\%M`
# this file - # https://github.com/soneups/setup-scripts/init.d/raw/master/piweather

case "$1" in 
    start)
        echo "Starting PiWeather..."
        python /home/pi/piweather/PublishTweet.py 'System booting...'
        ;;
    stop)
        echo "Stopping PiWeather..."
        python /home/pi/piweather/PublishTweet.py 'System initiated shutdown...'
        ;;
    *)
        echo "Usage: /etc/init.d/piweather start|stop"
        exit 1
        ;;
esac

exit 0
